// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmdchjpxtgofwruxhqby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtZGNoanB4dGdvZndydXhocWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTM5MjYsImV4cCI6MjA2NjMyOTkyNn0.FoCtnNFmMeOwwT2GFFiaW_gtfcGNWeVKn74wNDohvfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});